### ISSUE TITLE
Inaccurate hide block particles (bug)

### ISSUE THREAD

**Issue by bananstache** [Polyfrost/OverflowParticles#2]
In the block particle settings, when the options Hide Entity Running/Falling Particles is on and the mode is set to Visible Entities Only, rabbits will still show the running particles, despite being visible.

**Comment by Wyvest** [comment]
Make a ticket at discord.gg/polyfrost so we can track this further

**Comment by Wyvest** [comment]
https://github.com/Polyfrost/OverflowParticles/compare/5fb4db3d2553...179fb8e7e4b8
